CREATE TABLE EMPLOYEE(
    EMPID CHAR(4) PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    DESIGNATION CHAR(3),
    CITY VARCHAR(15) NOT NULL,
    CHECK (EMPID LIKE 'E%'),
    CHECK(DESIGNATION IN ('DBA','SWE','CEO','DEV','DOP'))
)
